base.url = https://automationexercise.com
gorest.base.url = https://gorest.co.in/
bearer.token = 5c91056a7a0aeef96d5aa559523562dd7fd7e442021e6a7d0975744e21deed7d
server = localhost
port = 5432
user = postgres